# Generated by Django 5.0.7 on 2024-08-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovar',
            name='ID_KetegorTovara',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='ID_TipTovara',
        ),
        migrations.DeleteModel(
            name='Kat_Tovara',
        ),
        migrations.DeleteModel(
            name='Tip_Tovara',
        ),
        migrations.DeleteModel(
            name='Tovar',
        ),
    ]
