# Generated by Django 5.0.7 on 2024-07-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tovar',
            old_name='ID_KetegorTovara',
            new_name='ID_KategorTovara',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='Image',
        ),
        migrations.AddField(
            model_name='statusdostupa',
            name='Opisanie_Dostupa',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tovar',
            name='Img_url',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='Chat_ID',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='Family',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='Name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
