# Generated by Django 5.0.7 on 2024-07-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_statusdostupa_opisanie_dostupa_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Chat_ID',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
