# Generated by Django 5.0.7 on 2024-08-04 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_baseotziv_id_user_alter_zakaz_id_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ID_Zakaz', models.IntegerField(blank=True, null=True)),
                ('ID_User', models.IntegerField(blank=True, null=True)),
                ('Gorod', models.CharField(max_length=255)),
                ('adres', models.TextField(blank=True, default='')),
                ('kontakt', models.CharField(blank=True, default='', max_length=255)),
                ('telefon', models.CharField(blank=True, default='', max_length=20)),
                ('adres_ediniy', models.BooleanField(default=False)),
                ('Nazvanie_adresa', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='zakaz',
            old_name='ID_Status',
            new_name='ID_Status_zakaza',
        ),
        migrations.RenameField(
            model_name='zakaz',
            old_name='Polucheno',
            new_name='Peredano_dostavka',
        ),
        migrations.RemoveField(
            model_name='zakaz',
            name='ID_Tovar',
        ),
        migrations.RemoveField(
            model_name='zakaz',
            name='Kolichestvo',
        ),
        migrations.AddField(
            model_name='zakaz',
            name='Data_peredano_v_dostavku',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='Data_sborki',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='Dostavka_nado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='Kolichestvo_klon',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='Peredano_v_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='Primechanie',
            field=models.TextField(blank=True, default='', max_length=600),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='Sobrano',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='Zakaz_Poluchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='Zakaz_dostavlen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='Zakaz_oplachen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='Zakaz_zakryt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='ID_adres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.adresa'),
        ),
        migrations.CreateModel(
            name='Otgruzka',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ID_Zakaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.zakaz')),
                ('tovar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tovar')),
            ],
        ),
    ]
