# Generated by Django 5.0.7 on 2024-07-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_users_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Family',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='Name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
