# Generated by Django 5.0.7 on 2024-08-04 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_baseotziv_id_user_alter_zakaz_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='StatusID',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.statusdostupa'),
        ),
    ]
