# Generated by Django 5.0.7 on 2024-08-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_customuser_statusid'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='Data_Zakaz_Poluchen',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='Data_Zakaz_oplachen',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='Data_Zakaz_zakryt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='DataDostavki',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='Data_peredano_v_dostavku',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='Data_sborki',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
