# Generated by Django 5.0.7 on 2024-08-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_zakaz_data_zakaz_poluchen_zakaz_data_zakaz_oplachen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhurnal_status_zakaza',
            name='Date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='zhurnal_status_zakaza',
            name='peredano',
            field=models.BooleanField(default=False),
        ),
    ]
