# Generated by Django 5.0.7 on 2024-08-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_zhurnal_status_zakaza_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='kolich_otzyv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='Profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='Rashod',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
