# Generated by Django 5.0.7 on 2024-08-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_baseotziv_reitingtovara'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseotziv',
            name='date_created',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
