# Generated by Django 5.0.7 on 2024-08-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cartitem_is_registered_cartitem_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
